### ISSUE TITLE
Project outdated?

### ISSUE THREAD

**Issue by Blitzilla** [Ludeon/RimWorld-ar#10]
I have reasons to doubt the project is up-to-date.
While working on files like Designators.xml I didn't see some features that were included in A14. I don't have the expertise nor the bandwidth to update the files even if I had the permissions to do so.

**Comment by mtimoustafa** [comment]
Yeah, I agree @Blitzilla. Looking at the project's pulse too, it seems this fork is getting really old. I don't have much knowledge with Rimworld's files (I just came here out of interest), but I'll see if I can't fork this and update it! Help is much appreciated, too :)

**Comment by mtimoustafa** [comment]
Just updated the repo to a17 so I'll mark this as closed.
