### ISSUE TITLE
hello  السلام عليكم 

### ISSUE THREAD

**Issue by waleeeeed2012** [Ludeon/RimWorld-ar#13]
I have a problem can you help me !!
arabic language is not cool 

ممكن  تساعدني 
اللغه العربيه في اللعبه  تكون  مقطعه  

exp.مثال
( ا  ب ح ر م)
mean  hello ( مرحبا )
how we can fix it
ty

**Comment by waleeeeed2012** [comment]
how can i contact with TynanSylvester maybe if he saw alot of people want that he will help us

**Comment by Reyakou** [comment]
This is what he said about the problem 
“Although I'm afraid this really isn't a high priority and could create a lot of UI work. So I'll keep it in mind, but don't anticipate it soon. Sorry about that. ”
You can @ him but i dont recommend it you will just waste time for both of you.

**Comment by 3koozy** [comment]
I am interested s well. you can count me in.

**Comment by waleeeeed2012** [comment]
feelsbadman

**Comment by waleeeeed2012** [comment]
So ..  Are we should wait more years :( ?

**Comment by mtimoustafa** [comment]
You can always look further into the issue and see if there's a really easy way of integrating a fix into the existing game, then talk to Ludeon about it and see how far you can take it. I'd do that myself, but honestly I don't have much free time right now.

**Comment by mtimoustafa** [comment]
This issue is a duplicate of https://github.com/Ludeon/RimWorld-ar/issues/11 so I'll close this one and track progress in the other one.
